# Generated by Django 2.1.15 on 2020-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190326_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob_city',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob_state',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mob',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tot_exp_mon',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tot_exp_yr',
            field=models.CharField(blank=True, default='', max_length=78, null=True),
        ),
    ]
