# Generated by Django 3.0.2 on 2020-01-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0007_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
